name: Shaderpulse tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache LLVM build
      uses: actions/cache@v3
      id: llvm-cache
      with:
        path: llvm-project/build
        key: ${{ runner.os }}-llvm-${{ hashFiles('llvm-project/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-llvm-

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25'

    - name: Build LLVM and MLIR
      if: steps.llvm-cache.outputs.cache-hit != 'true'
      run: |
        cmake -S llvm-project/llvm -B llvm-project/build -DLLVM_ENABLE_PROJECTS=mlir -G Ninja
        cmake --build llvm-project/build

    - name: Configure CMake for Shaderpulse
      run: cmake -B build -DENABLE_CODEGEN=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build Shaderpulse
      run: cmake --build build --config Release

    - name: Run CTest
      run: ctest --test-dir build/test --output-on-failure

    - name: Run CodeGen tests
      run: test/CodeGen/run_tests.sh
